name: Flutter Build for Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"

      - name: Check Flutter version
        run: flutter --version

      - name: Check Dart version
        run: dart --version

      # Listar a estrutura do projeto para verificar o caminho correto
      - name: List project directories
        run: |
          echo "Listing project directory structure:"
          ls -R
        continue-on-error: true  # Permitir que o processo continue mesmo que a listagem falhe

      # Instalar dependências do Flutter
      - name: Install dependencies
        run: |
          if [ -d "rustdesk/flutter" ]; then
            cd rustdesk/flutter
            flutter pub get
          else
            echo "Directory rustdesk/flutter not found"
            exit 1
          fi

      # Compilar o APK
      - name: Build APK
        run: |
          if [ -d "rustdesk/flutter" ]; then
            cd rustdesk/flutter
            flutter build apk --release
          else
            echo "Directory rustdesk/flutter not found"
            exit 1
          fi

      # Upload do APK
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-apk
          path: rustdesk/flutter/build/app/outputs/flutter-apk/app-release.apk
