name: Flutter Build for Android

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar
  workflow_dispatch:  # permite que você execute o workflow manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"  # Escolha uma versão do Flutter que suporte Dart SDK 3.1.0

      - name: Check Flutter version
        run: flutter --version

      - name: Check Dart version
        run: dart --version

      - name: Install dependencies
        run: |
          cd rustdesk/flutter
          flutter pub get

      - name: Build APK
        run: |
          cd rustdesk/flutter
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
          name: rustdesk-apk
          path: rustdesk/flutter/build/app/outputs/flutter-apk/app-release.apk
