name: Build RustDesk APK for Android (aarch64)

on:
  push:
    branches:
      - SerginhodaCevada-patch-1
  workflow_dispatch:

jobs:
  build-rustdesk-android:
    name: Build RustDesk Android APK for aarch64
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"

      - name: Check Flutter version
        run: flutter --version

      - name: Install dependencies
        run: |
          cd rustdesk/flutter
          flutter pub get

      - name: Build APK with Debug Logging
        run: |
          cd rustdesk/flutter
          flutter build apk --release --verbose --no-tree-shake-icons --build-number=1

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-apk
          path: rustdesk/flutter/build/app/outputs/flutter-apk/app-release.apk
