name: Flutter Build for Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-rustdesk-android:
    needs: [generate-bridge-linux]  # Dependência de outro job
    name: Build RustDesk Android APK ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { arch: aarch64, target: aarch64-linux-android, os: ubuntu-20.04, reltype: release, suffix: "" }
          - { arch: armv7, target: armv7-linux-androideabi, os: ubuntu-20.04, reltype: release, suffix: "" }
          - { arch: x86_64, target: x86_64-linux-android, os: ubuntu-20.04, reltype: release, suffix: "" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"

      - name: Check Flutter version
        run: flutter --version

      - name: Install dependencies
        run: |
          if [ -d "./flutter" ]; then
            cd flutter
            flutter pub get
          elif [ -d "rustdesk/flutter" ]; then
            cd rustdesk/flutter
            flutter pub get
          else
            echo "Directory flutter or rustdesk/flutter not found"
            exit 1
          fi

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: false
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: false

      - name: Build APK
        run: |
          if [ -d "./flutter" ]; then
            cd flutter
          elif [ -d "rustdesk/flutter" ]; then
            cd rustdesk/flutter
          else
            echo "Directory flutter or rustdesk/flutter not found"
            exit 1
          fi
          flutter build apk --release --verbose --no-tree-shake-icons --build-number=1

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-apk
          path: rustdesk/flutter/build/app/outputs/flutter-apk/app-release.apk
