name: Flutter Build

on:
  push:
    branches:
      - main  # Alvo para pushes no branch principal
  pull_request:
    branches:
      - main  # Alvo para pull requests no branch principal
  workflow_dispatch:  # Permite a execução manual do workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Verify network connection
      run: curl -I https://flutter.dev  # Verifica a conexão com a rede

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.3.9"  # Use uma versão fixa

    - name: Upgrade dependencies
      run: flutter pub upgrade

    - name: Install dependencies
      run: flutter pub get

    - name: Check Flutter version
      run: flutter --version

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: rustdesk-client-android-apk
        path: build/app/outputs/flutter-apk/app-release.apk
