name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: List directory contents
      run: ls -R  # Lista todos os arquivos e diretórios

    - name: Verify network connection
      run: curl -I https://flutter.dev

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.3.9"

    - name: Upgrade dependencies
      run: flutter pub upgrade
      working-directory: flutter  # Ajusta para o diretório correto

    - name: Install dependencies
      run: flutter pub get
      working-directory: flutter  # Ajusta para o diretório correto

    - name: Check Flutter version
      run: flutter --version
      working-directory: flutter  # Ajusta para o diretório correto

    - name: Build APK
      run: flutter build apk --release
      working-directory: flutter  # Ajusta para o diretório correto

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: rustdesk-client-android-apk
        path: flutter/build/app/outputs/flutter-apk/app-release.apk  # Ajusta para o caminho correto
