name: Flutter Build for Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Instala as dependências necessárias no ambiente
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
               clang \
               cmake \
               curl \
               gcc-multilib \
               git \
               g++ \
               g++-multilib \
               libayatana-appindicator3-dev \
               libasound2-dev \
               libc6-dev \
               libclang-10-dev \
               libgstreamer1.0-dev \
               libgstreamer-plugins-base1.0-dev \
               libgtk-3-dev \
               libpam0g-dev \
               libpulse-dev \
               libva-dev \
               libvdpau-dev \
               libxcb-randr0-dev \
               libxcb-shape0-dev \
               libxcb-xfixes0-dev \
               libxdo-dev \
               libxfixes-dev \
               llvm-10-dev \
               nasm \
               ninja-build \
               openjdk-11-jdk-headless \
               pkg-config \
               tree \
               wget 

      # Verifica a estrutura de diretórios após o checkout
      - name: List project directory structure
        run: |
          echo "Listing root project directory:"
          ls -R

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"

      - name: Check Flutter version
        run: flutter --version

      - name: Install Flutter dependencies
        run: |
          cd rustdesk/flutter || { echo "Directory rustdesk/flutter not found"; exit 1; }
          flutter pub get

      - name: Build APK
        run: |
          cd rustdesk/flutter || { echo "Directory rustdesk/flutter not found"; exit 1; }
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-apk
          path: rustdesk/flutter/build/app/outputs/flutter-apk/app-release.apk
