name: Flutter Build for Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4" # ou 3.7.12 se necessário

      - name: Check Flutter version
        run: flutter --version

      - name: Install dependencies
        run: |
          if [ -d "./flutter" ]; then
            cd flutter
            flutter pub get
          elif [ -d "rustdesk/flutter" ]; then
            cd rustdesk/flutter
            flutter pub get
          else
            echo "Directory flutter or rustdesk/flutter not found"
            exit 1
          fi

      - name: Build APK with Debug Logging
        run: |
          if [ -d "./flutter" ]; then
            cd flutter
          elif [ -d "rustdesk/flutter" ]; then
            cd rustdesk/flutter
          else
            echo "Directory flutter or rustdesk/flutter not found"
            exit 1
          fi
          flutter build apk --release --verbose --no-tree-shake-icons --build-number=1 --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-apk
          path: rustdesk/flutter/build/app/outputs/flutter-apk/app-release.apk
