name: Flutter Build for Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"

      - name: Check Flutter version
        run: flutter --version

      - name: Check Dart version
        run: dart --version

      - name: List project directories
        run: |
          echo "Listing project directory structure:"
          ls -R

      - name: Install dependencies
        run: |
          cd rustdesk/flutter || { echo "Directory rustdesk/flutter not found"; exit 1; }
          flutter pub get

      - name: Build APK
        run: |
          cd rustdesk/flutter || { echo "Directory rustdesk/flutter not found"; exit 1; }
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-apk
          path: rustdesk/flutter/build/app/outputs/flutter-apk/app-release.apk
